CREATE TABLE IF NOT EXISTS `[TABLENAME]` (
  `fondo` varchar(255) CHARACTER SET utf8 NOT NULL,
  `sec` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `epoca` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `seccion` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `fecha` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `serie` varchar(255) CHARACTER SET utf8 NOT NULL,
  `num_serie` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `tema` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `caja` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `expediente` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `lugar_r` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `remitente` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `destinatario` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `lugar d` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `titulo_nota` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `autor_nota` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `publicacion` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `asunto` text CHARACTER SET utf8,
  `keywords` text CHARACTER SET utf8,
  `tipo` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `medidas` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `fojas` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `sobre` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `notas` text CHARACTER SET utf8,
  `observaciones` text CHARACTER SET utf8
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;